### PR TITLE
Add pagination support for list-repos

### PR DESCRIPTION
**Pull request by mrueg**
See https://github.com/davedoesdev/dxf/issues/14

### CODE REVIEW

**Comment by davedoesdev** [comment]
@mrueg thanks. I was wondering whether to expose the pagination to the application. For large numbers of repos it would help I think.

**Comment by mrueg** [comment]
@davedoesdev okay, provided support to the application for that.

**Comment by davedoesdev** [comment]
@mrueg thanks. Let me take a look and add a test...

**Comment by davedoesdev** [comment]
@mrueg I did this slightly differently by supporting iteration and batch size in https://github.com/davedoesdev/dxf/commit/9e40cc7ab164f608bffe1b783773711f31776681

Let me know what you think.

**Comment by mrueg** [comment]
Change looks good to me, thanks!

**Comment by davedoesdev** [comment]
np, thanks for your help

**Pull request closed without merging**
