### PR TITLE
Type Lint Fix : pull_blob.<internal>.Chunks to Iterable<bytes/str>

### PR DESCRIPTION
**Pull request by serafdev**
I propose we remove the internal Chunks class and flatten out the function:

This fixes a few typing issues where the returned bytes are detected as objects by mypy:

- `error: Unsupported operand types for + ("bytes" and "object")  [operator]`
- `error: "object" has no attribute "decode"  [attr-defined]`

What you say?

### CODE REVIEW

**Comment by davedoesdev** [comment]
@serafdev thanks!
Will this change the behaviour from lazy to eager consumption of the chunks?

**Comment by davedoesdev** [comment]
Btw with latest pylint (3.0.1) and mypy (1.6.0) I don't get any lint or typecheck errors.

**Comment by serafdev** [comment]
@davedoesdev thanks for the quick response

> Will this change the behaviour from lazy to eager consumption of the chunks?

Correct, now that reading this it might be better to return an Iterator similar to the original, not sure

> Btw with latest pylint (3.0.1) and mypy (1.6.0) I don't get any lint or typecheck errors.

Try appending the chunks to a bytes type, can you check if you get the err on your side too?

```python
b = b""
for c in chunks:
    b += c  # type error happening here
```

**Comment by davedoesdev** [comment]
Ah, yes I'll try that when I get some time

**Comment by serafdev** [comment]
Hey @davedoesdev I think we could replace the `Chunks(object)` with `Chunks(Iterable[bytes])` instead and that fixes the mypy issue, here's a minimal reproducible code:

```python
from typing import Iterable


def iter_test() -> Iterable[bytes]:
    class Chunks(Iterable[bytes]):
        def __iter__(self):
            for x in [b"1", b"2", b"3"]:
                yield x

    return Chunks()


b: bytes = b""
for chunk in iter_test():
    b += chunk  #  no mypy error this time

print(b)

```

What do you think? That way we could only change 1 line of code instead of this whole refactor + we keep the lazy loading

**Comment by davedoesdev** [comment]
I'm not seeing any errors from mypy for this:

```python
rom typing import Iterable


def iter_test() -> Iterable[bytes]:
    class Chunks(object):
        def __iter__(self):
            for x in [b"1", b"2", b"3"]:
                yield x

    return Chunks()


b: bytes = b""
for chunk in iter_test():
    b += chunk  #  no mypy error this time

print(b)
```
david@david-laptop:~/dxf$ PATH="$PWD/venv/bin:$PATH" mypy /tmp/test.py 
Success: no issues found in 1 source file
```shell

**Comment by davedoesdev** [comment]
@serafdev I've made the change in 11.2.0, please let me know if it fixes your issue.

**Comment by serafdev** [comment]
Thanks @davedoesdev, actually the error was not the `object`, your code seemed OK already, it was actually the `Union` of a `Tuple` and an `Iterable``

My mistake here was that I did not assert the return type so mypy though I was appending `Union` to `bytes`

Added a check:

```python
if isinstance(chunk, bytes):
    b += chunk
```

And that worked, thank you for your quick responses!

**Pull request closed without merging**
