### PR TITLE
Romain dartigues delete

### PR DESCRIPTION
**Pull request by davedoesdev**
@romain-dartigues please review this PR which is based on yours (https://github.com/davedoesdev/dxf/pull/6)

I fixed the tests and in the case of deleting non-existing blob/alias, return ENOENT.

### CODE REVIEW

**Comment by romain-dartigues** [comment]
Looks good! I'll try to run everything again today and I'll keep you tuned.

**Comment by davedoesdev** [comment]
@romain-dartigues any luck?

**Comment by davedoesdev** [comment]
@romain-dartigues did this PR work for you?

**Comment by romain-dartigues** [comment]
Sorry, I'm ashamed to say I haven't found the time to work on it again, I promise to make you a feedback tomorrow. But when I reviewed your additions I didn't find anything to complain at first sight.

**Comment by romain-dartigues** [comment]
It's OK and does work well.
Thank you for your soft.

**Comment by davedoesdev** [comment]
@romain-dartigues thanks for your contribution, appreciate it

**Pull request merged**
