### PR TITLE
Read auth from file when user/password are not provided

### PR DESCRIPTION
**Pull request by cyrilleverrier**
Use dockercloud.api.auth to read credentials from ~/.docker/config.json

### CODE REVIEW

**Comment by davedoesdev** [comment]
@cyrilleverrier thanks for this PR, picking up your creds from docker would be useful. I wonder if we can make this a bit more generic, like allowing the caller to pass in the auth header. Then the calling application could do whatever it wanted.

**Comment by davedoesdev** [comment]
I can pick this up if you like, the easiest thing will be to allow passing headers into `authenticate()`.

**Comment by davedoesdev** [comment]
@cyrilleverrier `dxf` 5.1.0 now has an `authorization` argument to `authenticate()` which allows you to pass in the value of the `Authorization` HTTP header. So you should be able to pass in `'Basic ' + dockercloud.api.auth.load_from_file("~/.docker/config.json")` from your application.

For the CLI, there is a new `DXF_AUTHORIZATION` environment variable which does the same thing.

Please let me know if this works for you.

**Comment by cyrilleverrier** [comment]
@davedoesdev Thank you, I tried dxf 5.1.0 and it works as you explained.

I use the following code:
```
    auth = 'Basic ' + dockercloud.api.auth.load_from_file("~/.docker/config.json")
    dxf_obj = dxf.DXF("index.docker.io", repo="myorganizatiom/myimage)
    dxf_obj.authenticate(authorization=auth, actions=['pull'])
    return dxf_obj.list_aliases()
```

Maybe you can add this snippet to the README.md ?

**Comment by davedoesdev** [comment]
@cyrilleverrier done: https://github.com/davedoesdev/dxf#docker-cloud-authentication
Thanks for bringing this use case to my attention, appreciate it,

**Pull request closed without merging**
