### PR TITLE
Add OCIv1 media type support when fetching manifest

### PR DESCRIPTION
**Pull request by Ricordel**
# Disclaimer

I'm not very fluent with either this library or Docker registries in general. I don't know if I covered everything properly, or just my own use case :upside_down_face:

# A bit of context

Docker registries support several formats, among which
- docker v1 images (old and deprecated)
- docker v2 images (widely used for the last years as far as I understood)
- OCI v1, which has existed for a while but was not widely used until recently

For what I understood, the introduction of  the new `buildx` driver for Docker build (https://github.com/docker/buildx) has also caused the Docker client to upload images using the OCI v1 spec. I also suspect that the Docer Hub has started converting images in the background, as downloads that previously worked on some of our images using the DXF lib have broken a few days ago.

For instance, the Ubuntu images on the Docker Hub now use the new media types.

For more details about OCIv1 spec:
- https://github.com/opencontainers/image-spec/blob/main/image-index.md
- https://github.com/opencontainers/image-spec/blob/main/manifest.md

# What I did

When fetching a manifest (or manifest list), the client used to set Accept headers to accept docker-v1 or docker-v2 manifests mime types
- application/vnd.docker.distribution.manifest.v1+json
- application/vnd.docker.distribution.manifest.v2+json
- application/vnd.docker.distribution.manifest.list.v2+json

This commit adds the following mime types:
- application/vnd.oci.image.manifest.v1+json (https://github.com/opencontainers/image-spec/blob/main/manifest.md)
- application/vnd.oci.image.index.v1+json (https://github.com/opencontainers/image-spec/blob/main/image-index.md)
corresponding to "OCI registry v1" types.

OCI manifests being a backwards-compatible superset of Docker manifests v2, the rest of the code should continue to work fine (of course ignoring any extension specific to OCI v1). However, as I said, I'm not familiar with this codebase and I use only a few library functions, so I may be missing things. Please don't hesitate to point me in the right directions if there are some other changes required.

### CODE REVIEW

**Comment by davedoesdev** [comment]
@Ricordel thanks, this looks good. I'd like to test against an OCI registry. Currently the tests run against `registry:2` and `registry:2.2` (https://hub.docker.com/_/registry).
Do you know if there's a version of Docker Hub available locally which supports OCI images, or is that just the latest `registry:2`?

**Comment by davedoesdev** [comment]
@Ricordel thanks again, I've merged this via 4207aa1fc99b01387da1fbf62f6cd753c3889ab1 and is in v9.0.1.
Please let me know if it works for you.

**Comment by Ricordel** [comment]
Hello @davedoesdev, thank you for your merging and releasing so fast!

I can confirm that, for my use-case, it works perfectly using the 9.0.1 release.

B.t.w did you find a registry implementation to test with? I guess `registry:2.2` accepts this format, but I didn't try pushing artifacts with the new media types.

**Comment by davedoesdev** [comment]
I've tried various combinations, including the latest `registry:2`. They all (including the older `registry:2.2`) just return back as the Content-Type whatever was published in the manifest. I tried with OCI and previous docker v2 mimetype.

Where were you seeing rewriting happening?

**Comment by Ricordel** [comment]
I'm not 100% sure it happened, but almost, on some private image on the Docker Hub which we pushed months ago, and which I couldn't download anymore due to the media type not being recognized.

However there's a small chance that the image was indeed re-pushed and I didn't know about it, and I find doubtful that Docker would be scanning the whole hub to change formats, unless they plan to drop support for docker v2 in the coming months. Anyway, not a big deal now that the lib handles both formats.

**Pull request closed without merging**
